server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.217:3306/im?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: timesnew
  application:
    name: LGP-service


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      #defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: lgpcloud-service8002
    prefer-ip-address: true    #访问路径可以显示IP地址

info:
  app.name: lgp-servicecloud
  company.name: www.lgp.com
  build.artifactId: $project.artifactId$
  build.version: $project. version$

